### PR TITLE
sometimes (1 core) status beats nanny

### PR DESCRIPTION
**Pull request by rdallman**
fixes the wake of ruin created by https://github.com/iron-io/runner/pull/19 (_now_ passes worker tests)

### CODE REVIEW

**Comment by rdallman** [comment]
@nikhilm / @noqcks / @ccirello

**Comment by rdallman** [comment]
this will make some log lines show up about containers being inspected before they have exited, but we are removing with force stop, so we should expect them and be okay with them, or alternatively i could move this block above the inspect and we wouldn't see it, but the point of that inspect was to inspect similar cases so :shrug:

**Comment by rdallman** [comment]
sweet, done

**Comment by rdallman** [comment]
@nikhilm

**Comment by ccirello** [comment]
LGTM

**Pull request merged**
